import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { NextRequest } from "next/server";

function wrapText(text: string, font: any, fontSize: number, maxWidth: number): string[] {
  const lines: string[] = [];
  for (const paragraph of text.split("\n")) {
    if (paragraph.trim() === "") {
      lines.push("");
      continue;
    }
    const words = paragraph.split(" ");
    let current = "";
    for (const word of words) {
      const test = current ? `${current} ${word}` : word;
      const width = font.widthOfTextAtSize(test, fontSize);
      if (width > maxWidth && current) {
        lines.push(current);
        current = word;
      } else {
        current = test;
      }
    }
    if (current) lines.push(current);
  }
  return lines;
}

export async function GET(req: NextRequest) {
  const title = req.nextUrl.searchParams.get("title") || "Untitled Book";
  const content = req.nextUrl.searchParams.get("content") || "";

  const pdf = await PDFDocument.create();
  const fontRegular = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const pageWidth = 595;
  const pageHeight = 842;
  const margin = 60;
  const contentWidth = pageWidth - margin * 2;
  const fontSize = 11;
  const lineHeight = 16;
  const titleSize = 24;

  // Title page
  const titlePage = pdf.addPage([pageWidth, pageHeight]);
  const titleWidth = fontBold.widthOfTextAtSize(title, titleSize);
  titlePage.drawText(title, {
    x: (pageWidth - titleWidth) / 2,
    y: pageHeight / 2 + 40,
    size: titleSize,
    font: fontBold,
    color: rgb(0.1, 0.1, 0.1),
  });
  titlePage.drawText("Generated by MyBook", {
    x: (pageWidth - fontRegular.widthOfTextAtSize("Generated by MyBook", 10)) / 2,
    y: pageHeight / 2 - 10,
    size: 10,
    font: fontRegular,
    color: rgb(0.5, 0.5, 0.5),
  });

  // Content pages
  if (content) {
    const lines = wrapText(content, fontRegular, fontSize, contentWidth);
    let page = pdf.addPage([pageWidth, pageHeight]);
    let y = pageHeight - margin;

    for (const line of lines) {
      if (y < margin + lineHeight) {
        page = pdf.addPage([pageWidth, pageHeight]);
        y = pageHeight - margin;
      }

      if (line === "") {
        y -= lineHeight * 0.6;
        continue;
      }

      // Detect headings (lines starting with # or all caps short lines)
      const isHeading = line.startsWith("#") || (line.length < 80 && line === line.toUpperCase() && line.length > 3);
      const cleanLine = line.replace(/^#+\s*/, "");

      if (isHeading) {
        y -= 6;
        page.drawText(cleanLine, {
          x: margin,
          y,
          size: 13,
          font: fontBold,
          color: rgb(0.1, 0.1, 0.1),
        });
        y -= lineHeight + 4;
      } else if (line.startsWith("**") && line.endsWith("**")) {
        const boldText = line.slice(2, -2);
        page.drawText(boldText, {
          x: margin,
          y,
          size: fontSize,
          font: fontBold,
          color: rgb(0.15, 0.15, 0.15),
        });
        y -= lineHeight;
      } else {
        page.drawText(cleanLine, {
          x: margin,
          y,
          size: fontSize,
          font: fontRegular,
          color: rgb(0.15, 0.15, 0.15),
        });
        y -= lineHeight;
      }
    }
  }

  const bytes = await pdf.save();
  const buffer = new Uint8Array(bytes);

  return new Response(buffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${title.replace(/[^a-zA-Z0-9 ]/g, "").slice(0, 50)}.pdf"`,
    },
  });
}
