import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { rateLimitByUser } from "@/lib/rate-limit";

// Strip non-latin1 chars that pdf-lib can't handle with standard fonts
function sanitize(text: string): string {
  return text
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/\u2014/g, " — ")
    .replace(/\u2013/g, " - ")
    .replace(/\u2026/g, "...")
    .replace(/[\u2500-\u259F]/g, "")  // box drawing chars
    .replace(/[\u{1F000}-\u{1FFFF}]/gu, "") // emojis
    .replace(/[^\x00-\xFF]/g, ""); // strip anything outside latin1
}

function wrapText(text: string, font: any, fontSize: number, maxWidth: number): string[] {
  const lines: string[] = [];
  const words = text.split(" ");
  let current = "";
  for (const word of words) {
    const test = current ? `${current} ${word}` : word;
    try {
      const width = font.widthOfTextAtSize(test, fontSize);
      if (width > maxWidth && current) {
        lines.push(current);
        current = word;
      } else {
        current = test;
      }
    } catch {
      if (current) lines.push(current);
      current = word;
    }
  }
  if (current) lines.push(current);
  return lines;
}

export async function POST(req: Request) {
  // --- RATE LIMIT ---
  const rl = await rateLimitByUser("export-pdf", 30, 60 * 60 * 1000);
  if (rl.blocked) return rl.blocked;

  const { title = "Untitled Book", content = "" } = await req.json();

  const pdf = await PDFDocument.create();
  const fontRegular = await pdf.embedFont(StandardFonts.TimesRoman);
  const fontBold = await pdf.embedFont(StandardFonts.TimesRomanBold);
  const fontItalic = await pdf.embedFont(StandardFonts.TimesRomanItalic);

  const W = 595;
  const H = 842;
  const M = 72; // 1 inch margins
  const CW = W - M * 2;
  const bodySize = 11.5;
  const bodyLeading = 18;
  const h1Size = 18;
  const h2Size = 14;
  const h3Size = 12.5;

  const safeTitle = sanitize(title);

  // ── Title Page ──
  const tp = pdf.addPage([W, H]);
  // Decorative line
  tp.drawRectangle({ x: W / 2 - 80, y: H / 2 + 90, width: 160, height: 1.5, color: rgb(0.3, 0.3, 0.3) });
  // Title
  const titleLines = wrapText(safeTitle, fontBold, 28, CW);
  let ty = H / 2 + 60;
  for (const line of titleLines) {
    const tw = fontBold.widthOfTextAtSize(line, 28);
    tp.drawText(line, { x: (W - tw) / 2, y: ty, size: 28, font: fontBold, color: rgb(0.1, 0.1, 0.1) });
    ty -= 36;
  }
  // Decorative line
  tp.drawRectangle({ x: W / 2 - 80, y: ty - 10, width: 160, height: 1.5, color: rgb(0.3, 0.3, 0.3) });
  // Subtitle
  const sub = "Generated by Plot Ghost";
  const sw = fontItalic.widthOfTextAtSize(sub, 11);
  tp.drawText(sub, { x: (W - sw) / 2, y: ty - 40, size: 11, font: fontItalic, color: rgb(0.5, 0.5, 0.5) });

  // ── Content Pages ──
  if (content) {
    const rawLines = (content as string).split("\n");
    let page = pdf.addPage([W, H]);
    let y = H - M;
    let pageNum = 2;

    function newPage() {
      // Footer on current page
      const pn = String(pageNum - 1);
      const pnw = fontRegular.widthOfTextAtSize(pn, 9);
      page.drawText(pn, { x: (W - pnw) / 2, y: 36, size: 9, font: fontRegular, color: rgb(0.6, 0.6, 0.6) });
      page = pdf.addPage([W, H]);
      pageNum++;
      y = H - M;
    }

    function checkSpace(needed: number) {
      if (y - needed < M + 20) newPage();
    }

    for (const rawLine of rawLines) {
      const trimmed = sanitize(rawLine.trim());

      if (trimmed === "") {
        y -= bodyLeading * 0.5;
        continue;
      }

      // Heading detection
      const isH1 = trimmed.startsWith("# ") || trimmed.startsWith("# ");
      const isH2 = trimmed.startsWith("## ");
      const isH3 = trimmed.startsWith("### ");
      const isSeparator = /^[━─\-=]{3,}/.test(trimmed);

      if (isSeparator) {
        checkSpace(30);
        y -= 12;
        page.drawRectangle({ x: M, y: y, width: CW, height: 0.5, color: rgb(0.75, 0.75, 0.75) });
        y -= 18;
        continue;
      }

      if (isH3) {
        const text = trimmed.replace(/^###\s*/, "");
        checkSpace(40);
        y -= 14;
        const wrapped = wrapText(text, fontBold, h3Size, CW);
        for (const wl of wrapped) {
          checkSpace(20);
          page.drawText(wl, { x: M, y, size: h3Size, font: fontBold, color: rgb(0.15, 0.15, 0.15) });
          y -= 20;
        }
        y -= 4;
      } else if (isH2) {
        const text = trimmed.replace(/^##\s*/, "");
        checkSpace(50);
        y -= 18;
        const wrapped = wrapText(text, fontBold, h2Size, CW);
        for (const wl of wrapped) {
          checkSpace(22);
          page.drawText(wl, { x: M, y, size: h2Size, font: fontBold, color: rgb(0.12, 0.12, 0.12) });
          y -= 22;
        }
        y -= 6;
      } else if (isH1) {
        const text = trimmed.replace(/^#\s*/, "");
        checkSpace(60);
        y -= 24;
        page.drawRectangle({ x: M, y: y + h1Size + 8, width: CW, height: 0.5, color: rgb(0.8, 0.8, 0.8) });
        const wrapped = wrapText(text, fontBold, h1Size, CW);
        for (const wl of wrapped) {
          checkSpace(26);
          page.drawText(wl, { x: M, y, size: h1Size, font: fontBold, color: rgb(0.08, 0.08, 0.08) });
          y -= 26;
        }
        y -= 10;
      } else {
        // Body text — handle inline **bold**
        const clean = trimmed.replace(/\*\*/g, "");
        const isBoldLine = trimmed.startsWith("**") && trimmed.endsWith("**");
        const font = isBoldLine ? fontBold : fontRegular;
        const wrapped = wrapText(sanitize(clean), font, bodySize, CW);
        for (const wl of wrapped) {
          checkSpace(bodyLeading);
          try {
            page.drawText(wl, { x: M, y, size: bodySize, font, color: rgb(0.15, 0.15, 0.15) });
          } catch {
            // skip lines with problematic chars
          }
          y -= bodyLeading;
        }
      }
    }

    // Final page footer
    const pn = String(pageNum - 1);
    const pnw = fontRegular.widthOfTextAtSize(pn, 9);
    page.drawText(pn, { x: (W - pnw) / 2, y: 36, size: 9, font: fontRegular, color: rgb(0.6, 0.6, 0.6) });
  }

  const bytes = await pdf.save();
  const buffer = new Uint8Array(bytes);
  const safeName = safeTitle.replace(/[^a-zA-Z0-9 ]/g, "").slice(0, 50) || "book";

  return new Response(buffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${safeName}.pdf"`,
    },
  });
}
