import { jsPDF } from 'jspdf';
import prisma from './prisma';

interface ReportData {
  executiveSummary: string;
  keyMetrics: Record<string, any>;
  riskAlerts: string[];
  costTrends: any[];
  recommendations: string[];
}

export async function generateReportPDF(reportId: string): Promise<Uint8Array> {
  const report = await prisma.report.findUnique({
    where: { id: reportId },
    include: { organization: true },
  });
  if (!report) throw new Error('Report not found');

  const data: ReportData = JSON.parse(report.summary);
  const orgName = report.organization?.name || 'Unknown Organization';
  const doc = new jsPDF();
  let y = 20;

  const addPage = () => { doc.addPage(); y = 20; };
  const checkPage = (needed: number) => { if (y + needed > 270) addPage(); };
  const pageFooter = () => {
    const pages = doc.getNumberOfPages();
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(128);
      doc.text('Generated by KOSIQ AI Medical Economics Platform', 105, 285, { align: 'center' });
      doc.text(new Date().toISOString(), 105, 290, { align: 'center' });
      doc.text(`Page ${i} of ${pages}`, 195, 290, { align: 'right' });
    }
  };

  // Header
  doc.setFontSize(24);
  doc.setTextColor(0, 51, 102);
  doc.text('KOSIQ', 105, y, { align: 'center' });
  y += 8;
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text('AI Medical Economics Platform', 105, y, { align: 'center' });
  y += 12;

  // Report info
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text(report.title, 105, y, { align: 'center' });
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(80);
  doc.text(`Organization: ${orgName}`, 105, y, { align: 'center' });
  y += 5;
  doc.text(`Generated: ${new Date(report.generatedAt).toLocaleDateString()}`, 105, y, { align: 'center' });
  y += 5;
  doc.text(`Report Period: ${report.period}`, 105, y, { align: 'center' });
  y += 12;

  // Divider
  doc.setDrawColor(0, 51, 102);
  doc.setLineWidth(0.5);
  doc.line(15, y, 195, y);
  y += 10;

  // Executive Summary
  doc.setFontSize(14);
  doc.setTextColor(0, 51, 102);
  doc.text('Executive Summary', 15, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(0);
  const summaryLines = doc.splitTextToSize(data.executiveSummary || 'No summary available.', 170);
  doc.text(summaryLines, 15, y);
  y += summaryLines.length * 5 + 10;

  // Key Metrics Table
  checkPage(50);
  doc.setFontSize(14);
  doc.setTextColor(0, 51, 102);
  doc.text('Key Metrics', 15, y);
  y += 8;

  const metrics = data.keyMetrics || {};
  const metricRows = [
    ['Total Patients', String(metrics.totalPatients || 0)],
    ['Total Claims Cost', `$${(metrics.totalCost || 0).toLocaleString()}`],
    ['PMPM', `$${(metrics.pmpm || 0).toLocaleString()}`],
    ['Avg Risk Score', String(metrics.avgRiskScore || metrics.highRisk || 'N/A')],
    ['ER Visits', String(metrics.erVisits || 0)],
    ['Inpatient Stays', String(metrics.inpatient || 0)],
    ['ENS Events', String(metrics.ensEvents || 0)],
  ];

  doc.setFontSize(10);
  for (const [label, value] of metricRows) {
    doc.setTextColor(60);
    doc.text(label, 20, y);
    doc.setTextColor(0);
    doc.text(value, 100, y);
    y += 6;
  }
  y += 8;

  // Cost Breakdown
  checkPage(60);
  doc.setFontSize(14);
  doc.setTextColor(0, 51, 102);
  doc.text('Cost Breakdown by Category', 15, y);
  y += 8;

  // Fetch cost data from claims
  if (report.organizationId) {
    const [yr, mo] = report.period.split('-').map(Number);
    const claims = await prisma.claim.findMany({
      where: {
        patient: { organizationId: report.organizationId },
        claimDate: { gte: new Date(yr, mo - 1, 1), lt: new Date(yr, mo, 1) },
      },
    });

    const byType: Record<string, number> = {};
    claims.forEach(c => { byType[c.claimType] = (byType[c.claimType] || 0) + c.amount; });
    const categories = ['PCP', 'Specialist', 'ER', 'Inpatient', 'Pharmacy', 'Lab', 'Imaging', 'DME'];
    
    doc.setFontSize(9);
    doc.setTextColor(80);
    doc.text('Category', 20, y);
    doc.text('Amount', 100, y);
    doc.text('% of Total', 150, y);
    y += 2;
    doc.line(20, y, 180, y);
    y += 5;

    const total = Object.values(byType).reduce((s, v) => s + v, 0) || 1;
    doc.setTextColor(0);
    for (const cat of categories) {
      const amt = byType[cat] || 0;
      if (amt > 0) {
        doc.text(cat, 20, y);
        doc.text(`$${Math.round(amt).toLocaleString()}`, 100, y);
        doc.text(`${Math.round((amt / total) * 100)}%`, 150, y);
        y += 6;
      }
    }
    // Other categories not in the standard list
    for (const [cat, amt] of Object.entries(byType)) {
      if (!categories.includes(cat)) {
        doc.text(cat, 20, y);
        doc.text(`$${Math.round(amt).toLocaleString()}`, 100, y);
        doc.text(`${Math.round((amt / total) * 100)}%`, 150, y);
        y += 6;
      }
    }
    y += 8;

    // Top 10 High-Risk Patients
    checkPage(80);
    doc.setFontSize(14);
    doc.setTextColor(0, 51, 102);
    doc.text('Top 10 High-Risk Patients', 15, y);
    y += 8;

    const patients = await prisma.patient.findMany({
      where: { organizationId: report.organizationId },
      include: { claims: { where: { claimDate: { gte: new Date(yr, mo - 1, 1), lt: new Date(yr, mo, 1) } } } },
      orderBy: { riskScore: 'desc' },
      take: 10,
    });

    doc.setFontSize(8);
    doc.setTextColor(80);
    doc.text('Name', 20, y);
    doc.text('Risk', 80, y);
    doc.text('Conditions', 100, y);
    doc.text('Cost', 170, y);
    y += 2;
    doc.line(20, y, 190, y);
    y += 5;

    doc.setTextColor(0);
    for (const p of patients) {
      checkPage(8);
      const cost = p.claims.reduce((s, c) => s + c.amount, 0);
      let conds = '';
      try { conds = JSON.parse(p.conditions).slice(0, 2).join(', '); } catch {}
      doc.text(`${p.firstName} ${p.lastName}`, 20, y);
      doc.text(String(p.riskScore), 80, y);
      doc.text(doc.splitTextToSize(conds, 60)[0] || '', 100, y);
      doc.text(`$${Math.round(cost).toLocaleString()}`, 170, y);
      y += 6;
    }
    y += 8;
  }

  // AI Recommendations
  checkPage(40);
  doc.setFontSize(14);
  doc.setTextColor(0, 51, 102);
  doc.text('AI Recommendations', 15, y);
  y += 8;

  doc.setFontSize(10);
  doc.setTextColor(0);
  const recs = data.recommendations || [];
  if (recs.length === 0) {
    doc.text('No recommendations available for this period.', 20, y);
    y += 6;
  } else {
    recs.forEach((rec, i) => {
      checkPage(15);
      const lines = doc.splitTextToSize(`${i + 1}. ${rec}`, 165);
      doc.text(lines, 20, y);
      y += lines.length * 5 + 3;
    });
  }

  // Risk Alerts
  if (data.riskAlerts && data.riskAlerts.length > 0) {
    checkPage(30);
    y += 5;
    doc.setFontSize(14);
    doc.setTextColor(0, 51, 102);
    doc.text('Risk Alerts', 15, y);
    y += 8;
    doc.setFontSize(10);
    doc.setTextColor(0);
    data.riskAlerts.forEach(alert => {
      checkPage(10);
      const lines = doc.splitTextToSize(`• ${alert}`, 165);
      doc.text(lines, 20, y);
      y += lines.length * 5 + 2;
    });
  }

  pageFooter();

  return new Uint8Array(doc.output('arraybuffer'));
}
