import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const { title, content, author } = await req.json();
    if (!title || !content) {
      return NextResponse.json({ error: "Missing title or content" }, { status: 400 });
    }

    const epub = await import("epub-gen-memory");
    const createEpub = epub.default || epub;

    // Split content into chapters
    const chapters: { title: string; content: string }[] = [];
    const chapterRegex = /^#{1,2}\s+(.+)$/gm;
    const matches = [...content.matchAll(chapterRegex)];

    if (matches.length > 0) {
      for (let i = 0; i < matches.length; i++) {
        const chapterTitle = matches[i][1].trim();
        const start = matches[i].index! + matches[i][0].length;
        const end = i + 1 < matches.length ? matches[i + 1].index! : content.length;
        const chapterContent = content.slice(start, end).trim();

        // Convert markdown to basic HTML
        const html = markdownToHtml(chapterContent);
        chapters.push({ title: chapterTitle, content: html });
      }
    } else {
      // No chapters found, treat as single chapter
      chapters.push({ title: title, content: markdownToHtml(content) });
    }

    const epubBuffer = await createEpub(
      {
        title,
        author: author || "Plot Ghost",
        publisher: "Plot Ghost",
        description: `Generated by Plot Ghost`,
        tocTitle: "Table of Contents",
        date: new Date().toISOString(),
        lang: "en",
        css: `
          body { font-family: Georgia, "Times New Roman", serif; line-height: 1.6; color: #1a1a1a; }
          h1 { font-size: 1.8em; margin-top: 1.5em; margin-bottom: 0.5em; }
          h2 { font-size: 1.4em; margin-top: 1.2em; margin-bottom: 0.4em; }
          h3 { font-size: 1.2em; margin-top: 1em; margin-bottom: 0.3em; }
          p { margin-bottom: 0.8em; text-indent: 1.5em; }
          p:first-child { text-indent: 0; }
          blockquote { margin: 1em 2em; font-style: italic; border-left: 3px solid #ccc; padding-left: 1em; }
          ul, ol { margin-bottom: 0.8em; padding-left: 2em; }
          li { margin-bottom: 0.3em; }
          strong { font-weight: bold; }
          em { font-style: italic; }
        `,
      },
      chapters
    );

    return new NextResponse(new Uint8Array(epubBuffer), {
      headers: {
        "Content-Type": "application/epub+zip",
        "Content-Disposition": `attachment; filename="${encodeURIComponent(title)}.epub"`,
      },
    });
  } catch (e: any) {
    console.error("EPUB export error:", e);
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}

function markdownToHtml(md: string): string {
  let html = md
    // Headers
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    // Bold and italic
    .replace(/\*\*\*(.+?)\*\*\*/g, "<strong><em>$1</em></strong>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    // Blockquotes
    .replace(/^> (.+)$/gm, "<blockquote>$1</blockquote>")
    // Horizontal rules
    .replace(/^---$/gm, "<hr/>")
    // Unordered lists
    .replace(/^[*-] (.+)$/gm, "<li>$1</li>")
    // Numbered lists
    .replace(/^\d+\. (.+)$/gm, "<li>$1</li>");

  // Wrap consecutive <li> in <ul>
  html = html.replace(/((?:<li>.*?<\/li>\n?)+)/g, "<ul>$1</ul>");

  // Paragraphs — wrap non-tagged lines
  const lines = html.split("\n");
  const result: string[] = [];
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    if (trimmed.startsWith("<")) {
      result.push(trimmed);
    } else {
      result.push(`<p>${trimmed}</p>`);
    }
  }

  return result.join("\n");
}
