import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  PageBreak,
  BorderStyle,
  TabStopPosition,
  TabStopType,
} from "docx";

export async function POST(req: Request) {
  const { title = "Untitled Book", content = "" } = await req.json();

  const children: Paragraph[] = [];

  // ── Title Page ──
  children.push(
    new Paragraph({ spacing: { before: 3000 } }),
    // Decorative line
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
      border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: "999999", space: 8 } },
      children: [],
    }),
    // Title
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [
        new TextRun({ text: title, bold: true, size: 60, font: "Georgia" }),
      ],
    }),
    // Decorative line
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
      border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: "999999", space: 8 } },
      children: [],
    }),
    // Subtitle
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [
        new TextRun({ text: "Generated by My Book", italics: true, size: 22, color: "888888", font: "Georgia" }),
      ],
    }),
    new Paragraph({ children: [new PageBreak()] })
  );

  // ── Table of Contents header ──
  // (will be auto-placed at start of content)

  // ── Parse Content ──
  if (content) {
    const lines = (content as string).split("\n");
    let inChapter = false;

    for (let i = 0; i < lines.length; i++) {
      const trimmed = lines[i].trim();

      // Empty line
      if (trimmed === "") {
        children.push(new Paragraph({ spacing: { after: 80 } }));
        continue;
      }

      // Separators
      if (/^[━─\-=]{3,}/.test(trimmed)) {
        children.push(
          new Paragraph({
            spacing: { before: 200, after: 200 },
            border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC", space: 6 } },
            children: [],
          })
        );
        continue;
      }

      // H1
      if (trimmed.startsWith("# ") && !trimmed.startsWith("## ")) {
        const text = trimmed.replace(/^#\s*/, "");
        if (inChapter) {
          children.push(new Paragraph({ children: [new PageBreak()] }));
        }
        inChapter = true;
        children.push(
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 480, after: 240 },
            border: { bottom: { style: BorderStyle.SINGLE, size: 2, color: "333333", space: 8 } },
            children: [
              new TextRun({ text, bold: true, size: 40, font: "Georgia", color: "1a1a1a" }),
            ],
          })
        );
        continue;
      }

      // H2
      if (trimmed.startsWith("## ")) {
        const text = trimmed.replace(/^##\s*/, "");
        children.push(
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 360, after: 160 },
            children: [
              new TextRun({ text, bold: true, size: 32, font: "Georgia", color: "2a2a2a" }),
            ],
          })
        );
        continue;
      }

      // H3
      if (trimmed.startsWith("### ")) {
        const text = trimmed.replace(/^###\s*/, "");
        children.push(
          new Paragraph({
            heading: HeadingLevel.HEADING_3,
            spacing: { before: 280, after: 120 },
            children: [
              new TextRun({ text, bold: true, italics: true, size: 28, font: "Georgia", color: "333333" }),
            ],
          })
        );
        continue;
      }

      // Bullet points
      if (trimmed.startsWith("- ") || trimmed.startsWith("• ")) {
        const text = trimmed.replace(/^[-•]\s*/, "");
        const runs = parseBoldRuns(text, 24);
        children.push(
          new Paragraph({
            spacing: { after: 60 },
            indent: { left: 360 },
            children: [
              new TextRun({ text: "•  ", size: 24, font: "Georgia" }),
              ...runs,
            ],
          })
        );
        continue;
      }

      // Numbered list
      const numMatch = trimmed.match(/^(\d+)\.\s+(.*)/);
      if (numMatch) {
        const runs = parseBoldRuns(numMatch[2], 24);
        children.push(
          new Paragraph({
            spacing: { after: 60 },
            indent: { left: 360 },
            children: [
              new TextRun({ text: `${numMatch[1]}.  `, bold: true, size: 24, font: "Georgia" }),
              ...runs,
            ],
          })
        );
        continue;
      }

      // Regular paragraph with bold handling
      const runs = parseBoldRuns(trimmed, 24);
      children.push(
        new Paragraph({
          spacing: { after: 120, line: 360 },
          children: runs,
        })
      );
    }
  }

  const doc = new Document({
    styles: {
      default: {
        document: {
          run: { font: "Georgia", size: 24, color: "222222" },
        },
      },
    },
    sections: [{
      properties: {
        page: {
          margin: { top: 1440, bottom: 1440, left: 1440, right: 1200 },
        },
      },
      children,
    }],
  });

  const buffer = await Packer.toBuffer(doc);
  const bytes = new Uint8Array(buffer);
  const safeName = title.replace(/[^a-zA-Z0-9 ]/g, "").slice(0, 50) || "book";

  return new Response(bytes, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "Content-Disposition": `attachment; filename="${safeName}.docx"`,
    },
  });
}

function parseBoldRuns(text: string, size: number): TextRun[] {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  const runs: TextRun[] = [];
  for (const part of parts) {
    if (part.startsWith("**") && part.endsWith("**")) {
      runs.push(new TextRun({ text: part.slice(2, -2), bold: true, size, font: "Georgia" }));
    } else if (part) {
      runs.push(new TextRun({ text: part, size, font: "Georgia" }));
    }
  }
  return runs;
}
