import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  PageBreak,
} from "docx";

export async function POST(req: Request) {
  const { title = "Untitled Book", content = "" } = await req.json();

  const children: Paragraph[] = [];

  // Title page
  children.push(
    new Paragraph({ spacing: { before: 4000 } }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({ text: title, bold: true, size: 56, font: "Georgia" }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 400 },
      children: [
        new TextRun({
          text: "Generated by MyBook",
          size: 22,
          color: "888888",
          font: "Georgia",
        }),
      ],
    }),
    new Paragraph({ children: [new PageBreak()] })
  );

  // Parse content
  if (content) {
    const lines = (content as string).split("\n");
    for (const line of lines) {
      const trimmed = line.trim();

      if (trimmed === "") {
        children.push(new Paragraph({ spacing: { after: 120 } }));
        continue;
      }

      if (trimmed.startsWith("### ")) {
        children.push(
          new Paragraph({
            heading: HeadingLevel.HEADING_3,
            spacing: { before: 240, after: 120 },
            children: [new TextRun({ text: trimmed.replace(/^###\s*/, ""), bold: true, size: 26, font: "Georgia" })],
          })
        );
      } else if (trimmed.startsWith("## ")) {
        children.push(
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 360, after: 160 },
            children: [new TextRun({ text: trimmed.replace(/^##\s*/, ""), bold: true, size: 30, font: "Georgia" })],
          })
        );
      } else if (trimmed.startsWith("# ")) {
        children.push(
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 480, after: 200 },
            children: [new TextRun({ text: trimmed.replace(/^#\s*/, ""), bold: true, size: 36, font: "Georgia" })],
          })
        );
      } else if (trimmed.startsWith("━") || trimmed.startsWith("---")) {
        children.push(new Paragraph({ spacing: { before: 200, after: 200 } }));
      } else {
        const parts = trimmed.split(/(\*\*[^*]+\*\*)/g);
        const runs: TextRun[] = [];
        for (const part of parts) {
          if (part.startsWith("**") && part.endsWith("**")) {
            runs.push(new TextRun({ text: part.slice(2, -2), bold: true, size: 24, font: "Georgia" }));
          } else {
            runs.push(new TextRun({ text: part, size: 24, font: "Georgia" }));
          }
        }
        children.push(new Paragraph({ spacing: { after: 120 }, children: runs }));
      }
    }
  }

  const doc = new Document({
    sections: [{
      properties: { page: { margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } } },
      children,
    }],
  });

  const buffer = await Packer.toBuffer(doc);
  const bytes = new Uint8Array(buffer);

  return new Response(bytes, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "Content-Disposition": `attachment; filename="${title.replace(/[^a-zA-Z0-9 ]/g, "").slice(0, 50)}.docx"`,
    },
  });
}
