'use client';
import DashboardLayout from '@/components/DashboardLayout';
import Modal from '@/components/Modal';
import { useToast } from '@/components/Toast';
import { useState, useMemo } from 'react';

const investigators = ['Sarah Mitchell', 'James Rodriguez', 'Emily Chen', 'Marcus Johnson', 'Lisa Park'];
const investigationStatuses = ['Open', 'In Progress', 'Under Review', 'Closed - Confirmed', 'Closed - Dismissed'] as const;

const investigations = Array.from({ length: 35 }, (_, i) => ({
  caseNumber: `FI-2026-${String(100 + i).padStart(4, '0')}`,
  title: ['Systematic upcoding pattern', 'Unbundling of surgical codes', 'Duplicate billing across facilities', 'Phantom billing for DME', 'Kickback referral network', 'Modifier abuse pattern', 'Place of service fraud', 'Identity theft billing'][i % 8],
  alertCount: 2 + (i % 7),
  investigator: investigators[i % investigators.length],
  status: investigationStatuses[i % investigationStatuses.length],
  provider: ['Miami Primary Care Associates', 'South Florida Specialists', 'Coral Gables Medical Group', 'Aventura Health Center', 'Doral Medical Center'][i % 5],
  estimatedExposure: Math.round(15000 + Math.random() * 250000),
  recoveryAmount: i % 5 < 3 ? Math.round(8000 + Math.random() * 120000) : 0,
  openDate: `2026-${String(1 + (i % 3)).padStart(2, '0')}-${String(1 + (i % 28)).padStart(2, '0')}`,
  closeDate: i % 5 >= 3 ? `2026-03-${String(1 + (i % 10)).padStart(2, '0')}` : null,
  timeline: [
    { date: '2026-01-15', event: 'Alert generated by AI engine', by: 'System' },
    { date: '2026-01-16', event: 'Investigation opened', by: investigators[i % investigators.length] },
    { date: '2026-01-20', event: 'Provider records requested', by: investigators[i % investigators.length] },
    { date: '2026-02-01', event: 'Documentation reviewed', by: investigators[i % investigators.length] },
    { date: '2026-02-15', event: 'Findings documented', by: investigators[i % investigators.length] },
  ],
}));

const statusColor: Record<string, string> = { 'Open': 'bg-blue-100 text-blue-700', 'In Progress': 'bg-purple-100 text-purple-700', 'Under Review': 'bg-yellow-100 text-yellow-700', 'Closed - Confirmed': 'bg-red-100 text-red-700', 'Closed - Dismissed': 'bg-gray-100 text-gray-600' };

export default function InvestigationsPage() {
  const { showToast } = useToast();
  const [search, setSearch] = useState('');
  const [filterStatus, setFilterStatus] = useState('');
  const [selected, setSelected] = useState<typeof investigations[0] | null>(null);
  const [sortField, setSortField] = useState('openDate');
  const [sortDir, setSortDir] = useState<'asc'|'desc'>('desc');

  const filtered = useMemo(() => {
    let d = investigations.filter(inv =>
      (!search || inv.caseNumber.toLowerCase().includes(search.toLowerCase()) || inv.provider.toLowerCase().includes(search.toLowerCase()) || inv.investigator.toLowerCase().includes(search.toLowerCase())) &&
      (!filterStatus || inv.status === filterStatus)
    );
    d.sort((a, b) => {
      const av = (a as any)[sortField], bv = (b as any)[sortField];
      const cmp = typeof av === 'number' ? av - bv : String(av || '').localeCompare(String(bv || ''));
      return sortDir === 'asc' ? cmp : -cmp;
    });
    return d;
  }, [search, filterStatus, sortField, sortDir]);

  const toggleSort = (f: string) => { if (sortField === f) setSortDir(d => d === 'asc' ? 'desc' : 'asc'); else { setSortField(f); setSortDir('desc'); } };

  return (
    <DashboardLayout>
      <div className="max-w-7xl mx-auto">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-2xl font-semibold text-[#1d1d1f]">Investigations</h1>
            <p className="text-sm text-[#86868b]">Fraud investigation case management</p>
          </div>
          <button onClick={() => showToast('New investigation created')} className="px-4 py-2 bg-[#DC2626] text-white text-sm rounded-lg hover:bg-red-700">+ New Investigation</button>
        </div>

        <div className="grid grid-cols-4 gap-4 mb-6">
          {[
            { label: 'Open Cases', value: investigations.filter(i => i.status === 'Open').length, color: '#3B82F6' },
            { label: 'In Progress', value: investigations.filter(i => i.status === 'In Progress').length, color: '#7C3AED' },
            { label: 'Total Exposure', value: `$${(investigations.reduce((s, i) => s + i.estimatedExposure, 0) / 1000000).toFixed(1)}M`, color: '#DC2626' },
            { label: 'Total Recovered', value: `$${(investigations.reduce((s, i) => s + i.recoveryAmount, 0) / 1000000).toFixed(1)}M`, color: '#059669' },
          ].map((m, i) => (
            <div key={i} className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
              <p className="text-xs text-[#86868b] mb-1">{m.label}</p>
              <p className="text-2xl font-bold" style={{ color: m.color }}>{m.value}</p>
            </div>
          ))}
        </div>

        <div className="flex gap-3 mb-4">
          <input placeholder="Search cases, providers, investigators..." value={search} onChange={e => setSearch(e.target.value)} className="text-sm border border-gray-200 rounded-lg px-3 py-2 bg-white w-72" />
          <select value={filterStatus} onChange={e => setFilterStatus(e.target.value)} className="text-sm border border-gray-200 rounded-lg px-3 py-2 bg-white">
            <option value="">All Statuses</option>
            {investigationStatuses.map(s => <option key={s} value={s}>{s}</option>)}
          </select>
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
          <table className="w-full">
            <thead><tr className="bg-[#f5f5f7]">
              {[['caseNumber','Case #'],['title','Description'],['provider','Provider'],['investigator','Investigator'],['alertCount','Alerts'],['estimatedExposure','Exposure'],['recoveryAmount','Recovered'],['status','Status'],['openDate','Opened']].map(([f,l]) => (
                <th key={f} className="text-left text-[10px] font-semibold text-[#86868b] uppercase px-3 py-3 cursor-pointer hover:text-[#1d1d1f]" onClick={() => toggleSort(f)}>
                  {l} {sortField === f ? (sortDir === 'asc' ? '↑' : '↓') : ''}
                </th>
              ))}
            </tr></thead>
            <tbody>
              {filtered.map((inv, i) => (
                <tr key={i} className="border-t border-gray-50 hover:bg-[#f5f5f7]/50 cursor-pointer text-xs" onClick={() => setSelected(inv)}>
                  <td className="px-3 py-3 font-mono text-[#DC2626]">{inv.caseNumber}</td>
                  <td className="px-3 py-3 text-[#1d1d1f] max-w-[200px] truncate">{inv.title}</td>
                  <td className="px-3 py-3 text-[#6e6e73]">{inv.provider}</td>
                  <td className="px-3 py-3 text-[#1d1d1f]">{inv.investigator}</td>
                  <td className="px-3 py-3 text-center">{inv.alertCount}</td>
                  <td className="px-3 py-3 font-semibold text-[#DC2626]">${inv.estimatedExposure.toLocaleString()}</td>
                  <td className="px-3 py-3 font-semibold text-[#059669]">{inv.recoveryAmount ? `$${inv.recoveryAmount.toLocaleString()}` : '-'}</td>
                  <td className="px-3 py-3"><span className={`px-2 py-0.5 rounded-full text-[10px] font-medium ${statusColor[inv.status] || 'bg-gray-100 text-gray-600'}`}>{inv.status}</span></td>
                  <td className="px-3 py-3 text-[#86868b]">{inv.openDate}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <Modal open={!!selected} onClose={() => setSelected(null)} title={`Investigation ${selected?.caseNumber || ''}`} width="max-w-3xl">
          {selected && (
            <div className="space-y-6">
              <div className="grid grid-cols-2 gap-4">
                <div><p className="text-xs text-[#86868b]">Description</p><p className="text-sm font-medium">{selected.title}</p></div>
                <div><p className="text-xs text-[#86868b]">Provider</p><p className="text-sm font-medium">{selected.provider}</p></div>
                <div><p className="text-xs text-[#86868b]">Investigator</p><p className="text-sm font-medium">{selected.investigator}</p></div>
                <div><p className="text-xs text-[#86868b]">Status</p><p className="text-sm"><span className={`px-2 py-0.5 rounded-full text-xs font-medium ${statusColor[selected.status] || ''}`}>{selected.status}</span></p></div>
                <div><p className="text-xs text-[#86868b]">Est. Exposure</p><p className="text-sm font-bold text-[#DC2626]">${selected.estimatedExposure.toLocaleString()}</p></div>
                <div><p className="text-xs text-[#86868b]">Recovered</p><p className="text-sm font-bold text-[#059669]">{selected.recoveryAmount ? `$${selected.recoveryAmount.toLocaleString()}` : 'N/A'}</p></div>
              </div>
              <div>
                <h4 className="text-sm font-semibold text-[#1d1d1f] mb-3">Timeline</h4>
                <div className="space-y-3">
                  {selected.timeline.map((t, i) => (
                    <div key={i} className="flex items-start gap-3">
                      <div className="w-2 h-2 rounded-full bg-[#DC2626] mt-1.5 flex-shrink-0" />
                      <div>
                        <p className="text-xs text-[#86868b]">{t.date} · {t.by}</p>
                        <p className="text-sm text-[#1d1d1f]">{t.event}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
              <div className="flex gap-2">
                <button onClick={() => { showToast('Status updated'); setSelected(null); }} className="px-4 py-2 bg-[#DC2626] text-white text-sm rounded-lg hover:bg-red-700">Update Status</button>
                <button onClick={() => showToast('Evidence attached')} className="px-4 py-2 bg-gray-100 text-[#1d1d1f] text-sm rounded-lg hover:bg-gray-200">Attach Evidence</button>
              </div>
            </div>
          )}
        </Modal>
      </div>
    </DashboardLayout>
  );
}
